---
subtitle: "8-Monocle analysis and pseudotime estimation"
# bibliography: bib.bib
link-citations: yes
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output: 
  pdf_document:
    pandoc_args: 
      - '../common.yaml'
      - --listings
    includes: 
      in_header: '../preamble.tex'
    toc: true
    number_sections: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    df_print: tibble
---
```{r}
library(Seurat)
library(SeuratWrappers)
library(monocle3)
```

Load data
```{r}
IM_DTR3 <- readRDS(file = "C:/Users/domie/Documents/PhD_Domien_Vanneste_ULiege/PhD-ULiege/Bioinformatics/SingleCell/IM_DTR3_differentiation/only_IM_differentiation.with_SCENIC.seuratObject.Rds")
```

visualize data
```{r}
DimPlot(IM_DTR3, group.by = "cell.type2")
```

Rerun graph clustering
```{r}
IM_DTR3 <- RunUMAP(IM_DTR3, dims = 1:8, n.components = 3L)
DimPlot(IM_DTR3, group.by = "cell.type2")
```

```{r}
DefaultAssay(IM_DTR3) <- "RNA"
```

Create monocle 
```{r}
IM_DTR3.cds <- as.cell_data_set(IM_DTR3)

IM_DTR3.cds <- estimate_size_factors(IM_DTR3.cds)

IM_DTR3.cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(IM_DTR3[["RNA"]])

IM_DTR3.cds <- cluster_cells(cds = IM_DTR3.cds, reduction_method = "UMAP", resolution=0.5e-3) # don't play with resolution, # 
IM_DTR3.cds <- learn_graph(IM_DTR3.cds, use_partition = FALSE)
plot_cells(IM_DTR3.cds)
```

```{r}
all_cells <- choose_cells(IM_DTR3.cds, return_list = TRUE)
not_mono <- choose_graph_segments(IM_DTR3.cds, return_list = TRUE)
root <- setdiff(all_cells, not_mono$cells)
```

```{r}
IM_DTR3.cds <- order_cells(IM_DTR3.cds, reduction_method = "UMAP", root_cells = root)
```

```{r}
library(ggplot2)
plot_cells(
  cds = IM_DTR3.cds,
  color_cells_by = "pseudotime",
  show_trajectory_graph = FALSE
)& scale_color_viridis_c()
```

```{r}
library(plotly)
p1 <- plot_cells_3d(IM_DTR3.cds, color_cells_by="pseudotime", show_trajectory_graph = FALSE)
p1
#htmlwidgets::saveWidget(as_widget(p1), "3d_plot_pseudotime_all_cells.html")
```

Plot cell populations as 3D graph
```{r}
p2 <- plot_cells_3d(IM_DTR3.cds, color_cells_by="cell.type2", show_trajectory_graph = FALSE)
p2
htmlwidgets::saveWidget(as_widget(p2), "3d_plot_celltype2.html")
```

```{r}
saveRDS(IM_DTR3.cds, file = "C:/Users/domie/Documents/PhD_Domien_Vanneste_ULiege/PhD-ULiege/Bioinformatics/SingleCell/IM_DTR3_differentiation/only_IM_differentiation.with_Pseudotime.cds.Rds")
```

Add pseodotime to seurat object
```{r}
IM_DTR3 <- AddMetaData(object = IM_DTR3, metadata = IM_DTR3.cds@principal_graph_aux@listData$UMAP$pseudotime, col.name = "pseudotime")
```

```{r}
FeaturePlot(IM_DTR3, "pseudotime")& scale_color_viridis_c()
```
Save seurat object
```{r}
saveRDS(IM_DTR3, file = "C:/Users/domie/Documents/PhD_Domien_Vanneste_ULiege/PhD-ULiege/Bioinformatics/SingleCell/IM_DTR3_differentiation/only_IM_differentiation.with_SCENIC.with_Pseudotime.seuratObject.Rds")
```

Susbsetting differentiating cells
```{r}
Mono_to_IM <- choose_graph_segments(IM_DTR3.cds, return_list = TRUE)
Mono_to_IM.cds <- IM_DTR3.cds[,IM_DTR3.cds@colData@rownames %in% Mono_to_IM$cells]
```

```{r}
plot_cells(
  cds = Mono_to_IM.cds,
  color_cells_by = "pseudotime",
  show_trajectory_graph = FALSE
)& scale_color_viridis_c()
```

```{r}
library(tradeSeq)
library(magrittr)
# Get the closest vertice for every cell
y_to_cells <-  IM_DTR3.cds@principal_graph_aux$UMAP$pr_graph_cell_proj_closest_vertex %>%
  as.data.frame()
y_to_cells$cells <- rownames(y_to_cells)
y_to_cells$Y <- y_to_cells$V1


# Get the root vertices
# It is the same node as above
root <- IM_DTR3.cds@principal_graph_aux$UMAP$root_pr_nodes

principalgraph <- IM_DTR3.cds@principal_graph$UMAP

# Get the other endpoints
endpoints <- names(which(igraph::degree(principalgraph ) == 1))
endpoints <- endpoints[!endpoints %in% root]

# For each endpoint
cellWeights <- lapply(endpoints, function(endpoint) {
  # We find the path between the endpoint and the root
  path <- igraph::shortest_paths(principalgraph, root, endpoint)$vpath[[1]]
  path <- as.character(path)
  # We find the cells that map along that path
  df <- y_to_cells[y_to_cells$Y %in% path, ]
  df <- data.frame(weights = as.numeric(colnames(IM_DTR3.cds) %in% df$cells))
  colnames(df) <- endpoint
  return(df)
  }) %>% do.call(what = 'cbind', args = .) %>%
    as.matrix()
rownames(cellWeights) <- colnames(IM_DTR3.cds)
pseudotime <- matrix(IM_DTR3.cds@principal_graph_aux$UMAP$pseudotime, ncol = ncol(cellWeights),
                     nrow = ncol(IM_DTR3.cds), byrow = FALSE)
rownames(pseudotime) <- colnames(IM_DTR3.cds)
```


```{r}
counts <- IM_DTR3.cds@assays@data$counts
```

```{r}
cellWeights_sub <- cellWeights[colnames(Mono_to_IM.cds),]
pseudotime_sub <- pseudotime[colnames(Mono_to_IM.cds),]
counts_sub <- Mono_to_IM.cds@assays@data$counts




sce <- fitGAM(counts = counts_sub, pseudotime = pseudotime_sub, cellWeights = cellWeights_sub, genes = VariableFeatures(IM_DTR3))

```


```{r}
sce <- readRDS(file = "C:/Users/domie/Documents/PhD_Domien_Vanneste_ULiege/PhD-ULiege/Bioinformatics/SingleCell/IM_DTR3_differentiation/sce_filteredCells_filteredGenes.after_fitGAM.sce.Rds")
```

```{r}
endRes <- diffEndTest(sce)
```

```{r}
scenic <- IM_DTR3@assays$scenic@data
scenic_sub <- scenic[,colnames(Mono_to_IM.cds)]
```


```{r}
plotSmoothers(sce, scenic_sub, "Maf")
```

```{r}
sce <- readRDS(file = "C:/Users/domie/Documents/PhD_Domien_Vanneste_ULiege/PhD-ULiege/Bioinformatics/SingleCell/IM_DTR3_differentiation/sce.after_fitGAM.sce")
```

```{r}
counts <- IM_DTR3.cds@assays@data$counts
counts_sub <- counts[,colnames(sce)]
```

```{r}
plotSmoothers(sce, counts_sub, "Mafb")
```

```{r}
sub <- IM_DTR3.cds[,colnames(sce)]
```


```{r}
library(ggplot2)
plot_cells(
  cds = sub,
  color_cells_by = "pseudotime",
  show_trajectory_graph = FALSE
)& scale_color_viridis_c()
```

